### ISSUE TITLE
Not all colours can be set through webchat config

### ISSUE THREAD

**Issue by stu-greenshoots** [opendialogai/webchat#131]
Some colours are overwritten in css and changing their value in webchat settings does not affect the webchat frontend.

Also, it would be nice to include more colours such as:
- button colour
- button hover colour
- minimize button colour

Outcome: on a "vanilla" install of OpenDialog all webchat settings changes via admin should be reflected on the webchat widget.

**Comment by nicolocaruso85** [comment]
https://github.com/opendialogai/vue-beautiful-chat/pull/13
https://github.com/opendialogai/webchat/pull/132
