### ISSUE TITLE
Inconsistent placement of callback_id in response messages 

### ISSUE THREAD

**Issue by stu-greenshoots** [opendialogai/webchat#92]
Sometimes it is placed in the main body, sometimes in data.

It should be consistently outside at the root of the body, not in data.

This will require an update in core

**Comment by nicolocaruso85** [comment]
Changes in webchat: https://github.com/opendialogai/webchat/pull/102
Changes in core: https://github.com/opendialogai/core/pull/162

**Comment by stu-greenshoots** [comment]
This has been merged in
